import { Inter } from "next/font/google";
import { cn } from '@/lib/utils'
import "./globals.css";
import { LogoutButton } from '@/components/component/logout-button'
import Navbar from '@/components/component/navbar'

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
